name: gliderviz
channels:
  - conda-forge
dependencies:
  - python
  - datashader
  - geoviews
  - gsw
  - fsspec
  - hvplot
  - jupyterlab=2
  - jupyter-panel-proxy
  - netcdf4=1.5.4
  - numexpr
  - pandas
  - pip=20
  - pykrige
  - xarray
  - pip:
    - git+git://github.com/dhruvbalwada/GliderTools.git@add_spice
