name: gliderviz
channels:
  - conda-forge
dependencies:
  - python
  - datashader
  - geoviews
  - gsw
  - fsspec
  - holoviews=1.14.2
  - hvplot
  - jupyterlab=2
  - jupyter-panel-proxy
  - netcdf4=1.5.4
  - numexpr
  - pandas
  - pip=20
  - pykrige
  - pyarrow
  - xarray=0.16.2
  - intake
  - intake-parquet
  - pip:
    - git+git://github.com/dhruvbalwada/GliderTools.git@add_spice
